// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shift_Manager.Server.Infrastructure.Context;

#nullable disable

namespace Shift_Manager.Server.Migrations
{
    [DbContext(typeof(ShiftManagerDbContext))]
    [Migration("20260410093703_FixCascadePaths")]
    partial class FixCascadePaths
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shift_Manager.Server.Domain.Entities.Agente", b =>
                {
                    b.Property<int>("ID_Agente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Agente"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("Antiguedad")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Codigo_Agente")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Contacto")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("Disponibilidad")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Cuadrante")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PuestoAsignado")
                        .HasColumnType("int");

                    b.Property<string>("Rango")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ID_Agente");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("Codigo_Agente")
                        .IsUnique();

                    b.HasIndex("ID_Cuadrante");

                    b.ToTable("Agentes", t =>
                        {
                            t.HasTrigger("trg_Agentes_Auditoria");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Shift_Manager.Server.Domain.Entities.Cuadrante", b =>
                {
                    b.Property<int>("ID_Cuadrante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Cuadrante"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sector")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID_Cuadrante");

                    b.ToTable("Cuadrantes");
                });

            modelBuilder.Entity("Shift_Manager.Server.Domain.Entities.HistoricoCambio", b =>
                {
                    b.Property<int>("ID_Historico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Historico"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Registro")
                        .HasColumnType("int");

                    b.Property<string>("Tabla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID_Historico");

                    b.ToTable("HistoricoCambios");
                });

            modelBuilder.Entity("Shift_Manager.Server.Domain.Entities.Horario", b =>
                {
                    b.Property<int>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHorario"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("ID_Turno")
                        .HasColumnType("int");

                    b.Property<string>("IdAgente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IdAgente");

                    b.Property<int>("IdCuadrante")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TipoTurno")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdHorario");

                    b.HasIndex("ID_Turno");

                    b.HasIndex("IdCuadrante");

                    b.ToTable("Horarios", t =>
                        {
                            t.HasTrigger("trg_Horarios_Auditoria");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Shift_Manager.Server.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Shift_Manager.Server.Domain.Entities.Reporte", b =>
                {
                    b.Property<int>("ID_Reporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Reporte"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Agente")
                        .HasColumnType("int");

                    b.Property<int>("ID_Cuadrante")
                        .HasColumnType("int");

                    b.Property<int>("ID_Turno")
                        .HasColumnType("int");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Reporte");

                    b.HasIndex("ID_Agente");

                    b.HasIndex("ID_Cuadrante");

                    b.HasIndex("ID_Turno");

                    b.ToTable("Reportes", t =>
                        {
                            t.HasTrigger("trg_Reportes_Auditoria");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Shift_Manager.Server.Domain.Entities.Turno", b =>
                {
                    b.Property<int>("ID_Turno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Turno"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinReal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicioReal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaProgramadaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaProgramadaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Agente")
                        .HasColumnType("int");

                    b.Property<int>("ID_Cuadrante")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ID_Turno");

                    b.HasIndex("ID_Agente");

                    b.HasIndex("ID_Cuadrante");

                    b.ToTable("Turnos", t =>
                        {
                            t.HasTrigger("trg_Turnos_Auditoria");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Shift_Manager.Server.Domain.Entities.UsuarioSistema", b =>
                {
                    b.Property<int>("ID_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Usuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ID_Agente")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID_Usuario");

                    b.HasIndex("ID_Agente");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UsuariosSistema");
                });

            modelBuilder.Entity("Shift_Manager.Server.Domain.Entities.Agente", b =>
                {
                    b.HasOne("Shift_Manager.Server.Domain.Entities.Cuadrante", "Cuadrante")
                        .WithMany("Agentes")
                        .HasForeignKey("ID_Cuadrante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuadrante");
                });

            modelBuilder.Entity("Shift_Manager.Server.Domain.Entities.Horario", b =>
                {
                    b.HasOne("Shift_Manager.Server.Domain.Entities.Turno", "Turno")
                        .WithMany("Horarios")
                        .HasForeignKey("ID_Turno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shift_Manager.Server.Domain.Entities.Cuadrante", "Cuadrante")
                        .WithMany("Horarios")
                        .HasForeignKey("IdCuadrante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuadrante");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Shift_Manager.Server.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Shift_Manager.Server.Domain.Entities.UsuarioSistema", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Shift_Manager.Server.Domain.Entities.Reporte", b =>
                {
                    b.HasOne("Shift_Manager.Server.Domain.Entities.Agente", "Agente")
                        .WithMany("Reportes")
                        .HasForeignKey("ID_Agente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shift_Manager.Server.Domain.Entities.Cuadrante", "Cuadrante")
                        .WithMany("Reportes")
                        .HasForeignKey("ID_Cuadrante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shift_Manager.Server.Domain.Entities.Turno", "Turno")
                        .WithMany("Reportes")
                        .HasForeignKey("ID_Turno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agente");

                    b.Navigation("Cuadrante");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Shift_Manager.Server.Domain.Entities.Turno", b =>
                {
                    b.HasOne("Shift_Manager.Server.Domain.Entities.Agente", "Agente")
                        .WithMany("Turnos")
                        .HasForeignKey("ID_Agente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shift_Manager.Server.Domain.Entities.Cuadrante", "Cuadrante")
                        .WithMany("Turnos")
                        .HasForeignKey("ID_Cuadrante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agente");

                    b.Navigation("Cuadrante");
                });

            modelBuilder.Entity("Shift_Manager.Server.Domain.Entities.UsuarioSistema", b =>
                {
                    b.HasOne("Shift_Manager.Server.Domain.Entities.Agente", "Agente")
                        .WithMany("UsuariosSistema")
                        .HasForeignKey("ID_Agente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Agente");
                });

            modelBuilder.Entity("Shift_Manager.Server.Domain.Entities.Agente", b =>
                {
                    b.Navigation("Reportes");

                    b.Navigation("Turnos");

                    b.Navigation("UsuariosSistema");
                });

            modelBuilder.Entity("Shift_Manager.Server.Domain.Entities.Cuadrante", b =>
                {
                    b.Navigation("Agentes");

                    b.Navigation("Horarios");

                    b.Navigation("Reportes");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Shift_Manager.Server.Domain.Entities.Turno", b =>
                {
                    b.Navigation("Horarios");

                    b.Navigation("Reportes");
                });

            modelBuilder.Entity("Shift_Manager.Server.Domain.Entities.UsuarioSistema", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
